version: '3.8'
services:
  gateway:
    build: gateway/
    container_name: share-it-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
#      - TZ=Europe/Moscow

  server:
    build: server/
    container_name: share-it-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
#      - TZ=Europe/Moscow

  db:
    image: postgres:14.5-alpine3.16
    container_name: share-it-postgres
    ports:
      - "6541:5432"
#    volumes:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shareit
#      - TZ=Europe/Moscow